### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Myndale** [midstar/jdmenubar#1]
**Issue:** Adding a standard document type declaration to a page causes jdmenubar drop-down menus to lose their positioning.
**Browsers:** Google Chrome Version 99.0.4844.84 (Official Build) (64-bit), Microsoft Edge Version 99.0.1150.55 (Official build) (64-bit)
**Reproduceability:** 100%
**Steps to reproduce:** Add the tag `<!DOCTYPE html>` to the start of the top-most html file.
**Observed behaviour:** Drop-down menus appear in the wrong position:
![image](https://user-images.githubusercontent.com/3477140/160942658-273efabc-e1f9-41c6-9c0c-fa2f346bd19e.png)
**Expected behaviour:** Drop-down menus should appear in the same position as when the DOCTYPE tag isn't present:
![image](https://user-images.githubusercontent.com/3477140/160942706-3183ecb9-dc62-4286-ac23-cbc44710ccce.png)
**Cause:** This is due to a minor bug in the jdmenubar.js file. The presence of the DOCTYPE tag causes the browser to apply more strict rules to element attributes, including the requirement that units always be specified for `left` and `top` element attributes. The code that positions the menus does not specify units:
```
    if (subMenuElement.jdmenu_parentMenu === myself.menuBarElement) {
      // Drop down
      subMenuElement.style.left = pos.left;
      subMenuElement.style.top = pos.bottom;
    } else {
      // Show right
      subMenuElement.style.left = pos.right;
      subMenuElement.style.top = pos.top;
    }
```
**Proposed fix:** The above code block needs to be modified to specify units:
```
    if (subMenuElement.jdmenu_parentMenu === myself.menuBarElement) {
      // Drop down
      subMenuElement.style.left = pos.left + "px";
      subMenuElement.style.top = pos.bottom + "px";
    } else {
      // Show right
      subMenuElement.style.left = pos.right + "px";
      subMenuElement.style.top = pos.top + "px";
    }
```

**Comment by midstar** [comment]
Thank you for the feedback. I have corrected the issue on master based on your suggestion.

**Comment by Myndale** [comment]
Thanks! 👍
